---
micronaut:
    application:
        name: gormdemo
                
#Uncomment to set server port
#    server:
#        port: 8080

---
datasources.default: {}
---
hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.postgresql.Driver
